sudo: required
language: go
go:
  - 1.9

notifications:
  email: false

services:
  - docker

env:
  - DEP_VERSION="0.4.1"

before_install:
  - curl -L -s https://github.com/golang/dep/releases/download/v${DEP_VERSION}/dep-linux-amd64 -o $GOPATH/bin/dep
  - chmod +x $GOPATH/bin/dep
  - chmod +x ./all-test-with-coverage.sh
  - chmod +x ./swagger-validate.sh
  - chmod +x ./build.sh
  - chmod +x ./docker-build.sh
  - chmod +x ./docker-push.sh
  - mkdir build

install:
  - dep ensure
  - go get github.com/golang/lint/golint
  - go get honnef.co/go/tools/cmd/megacheck
  - go get github.com/fzipp/gocyclo
  - go get -u github.com/gobuffalo/packr/...
  - go get -u github.com/go-swagger/go-swagger/cmd/swagger

script:
  - ./swagger-validate.sh
  - ./all-test-with-coverage.sh
  - go vet ./...
  - megacheck ./...
  - gocyclo -over 10 $(find . -iname '*.go' -type f | grep -v /vendor/)
  - golint -set_exit_status $(go list ./... | grep -v mock)

after_success:
  - bash <(curl -s https://codecov.io/bash)

before_deploy:
  - docker pull karalabe/xgo-latest
  - go get github.com/karalabe/xgo
  - ./build.sh ${TRAVIS_TAG#v}
  - ./docker-build.sh ${TRAVIS_TAG#v}

deploy:
  - provider: releases
    api_key: $GH_TOKEN
    file_glob: true
    file: build/*.zip
    skip_cleanup: true
    on:
      tags: true
  - provider: script
    script: bash docker-push.sh
    skip_cleanup: true
    on:
        tags: true